"""Add session_document_texts table

Revision ID: 02ba3f12a589
Revises: 5b3dcdf5c5aa
Create Date: 2026-03-17 22:08:25.783343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02ba3f12a589'
down_revision: Union[str, Sequence[str], None] = '5b3dcdf5c5aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_document_texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('doc_type', sa.String(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_document_texts_id'), 'session_document_texts', ['id'], unique=False)
    op.create_index(op.f('ix_session_document_texts_session_id'), 'session_document_texts', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_document_texts_session_id'), table_name='session_document_texts')
    op.drop_index(op.f('ix_session_document_texts_id'), table_name='session_document_texts')
    op.drop_table('session_document_texts')
    # ### end Alembic commands ###
