"""add full_name mobile and country to users

Revision ID: 0aed0adb329c
Revises: 35f03721b8c9
Create Date: 2026-02-20 22:07:06.373812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aed0adb329c'
down_revision: Union[str, Sequence[str], None] = '35f03721b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('mobile_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'country')
    op.drop_column('users', 'mobile_number')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
