"""add_monthly_token_guard_to_user_usage

Revision ID: 2a9e23e4f9fe
Revises: aa386e2f3ad8
Create Date: 2026-03-29 01:25:20.883632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a9e23e4f9fe'
down_revision: Union[str, Sequence[str], None] = 'aa386e2f3ad8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_session_document_texts_id")
    op.execute("DROP INDEX IF EXISTS ix_session_document_texts_session_id")
    op.execute("DROP TABLE IF EXISTS session_document_texts CASCADE")

    # Re-create constraints safely or drop them if they exist
    # For constraints, we can use a helper or just execute raw SQL
    op.execute("ALTER TABLE chat_messages DROP CONSTRAINT IF EXISTS chat_messages_session_id_fkey")
    op.create_foreign_key(None, 'chat_messages', 'chat_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    
    op.execute("ALTER TABLE feedback DROP CONSTRAINT IF EXISTS feedback_message_id_fkey")
    op.create_foreign_key(None, 'feedback', 'chat_messages', ['message_id'], ['id'], ondelete='CASCADE')
    
    op.execute("ALTER TABLE shared_sessions DROP CONSTRAINT IF EXISTS shared_sessions_session_id_fkey")
    op.create_foreign_key(None, 'shared_sessions', 'chat_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    
    op.add_column('user_usage', sa.Column('monthly_tokens_used', sa.BigInteger(), nullable=True))
    op.add_column('user_usage', sa.Column('monthly_reset_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_usage', 'monthly_reset_date')
    op.drop_column('user_usage', 'monthly_tokens_used')
    op.drop_constraint(None, 'shared_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('shared_sessions_session_id_fkey'), 'shared_sessions', 'chat_sessions', ['session_id'], ['id'])
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.create_foreign_key(op.f('feedback_message_id_fkey'), 'feedback', 'chat_messages', ['message_id'], ['id'])
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key(op.f('chat_messages_session_id_fkey'), 'chat_messages', 'chat_sessions', ['session_id'], ['id'])
    op.create_table('session_document_texts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('case_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('doc_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('extracted_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('session_document_texts_pkey'))
    )
    op.create_index(op.f('ix_session_document_texts_session_id'), 'session_document_texts', ['session_id'], unique=False)
    op.create_index(op.f('ix_session_document_texts_id'), 'session_document_texts', ['id'], unique=False)
    # ### end Alembic commands ###
