"""replace shared_message with shared_session

Revision ID: 35f03721b8c9
Revises: 14d520fac86b
Create Date: 2026-02-20 21:10:37.391065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35f03721b8c9'
down_revision: Union[str, Sequence[str], None] = '14d520fac86b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_sessions_id'), 'shared_sessions', ['id'], unique=False)
    op.drop_index(op.f('ix_shared_messages_id'), table_name='shared_messages')
    op.drop_table('shared_messages')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_messages',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], name=op.f('shared_messages_message_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('shared_messages_pkey'))
    )
    op.create_index(op.f('ix_shared_messages_id'), 'shared_messages', ['id'], unique=False)
    op.drop_index(op.f('ix_shared_sessions_id'), table_name='shared_sessions')
    op.drop_table('shared_sessions')
    # ### end Alembic commands ###
