"""Add verification columns to users

Revision ID: 5b3dcdf5c5aa
Revises: 0e5ed8202fc9
Create Date: 2026-03-08 11:43:00.974354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b3dcdf5c5aa'
down_revision: Union[str, Sequence[str], None] = '0e5ed8202fc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_chunks_chunk_type'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_external_id'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_id'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_column('chat_messages', 'source_ids')
    op.drop_column('chat_messages', 'party_citations')
    op.drop_column('chat_messages', 'judgment_ids')
    op.drop_index(op.f('ix_users_verification_token'), table_name='users')
    op.create_index(op.f('ix_users_verification_token'), 'users', ['verification_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_verification_token'), table_name='users')
    op.create_index(op.f('ix_users_verification_token'), 'users', ['verification_token'], unique=False)
    op.add_column('chat_messages', sa.Column('judgment_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('chat_messages', sa.Column('party_citations', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('chat_messages', sa.Column('source_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('chunk_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('external_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('knowledge_chunks_pkey'))
    )
    op.create_index(op.f('ix_knowledge_chunks_id'), 'knowledge_chunks', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_external_id'), 'knowledge_chunks', ['external_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_chunk_type'), 'knowledge_chunks', ['chunk_type'], unique=False)
    # ### end Alembic commands ###
