"""Add Coupon model and update PaymentTransaction

Revision ID: 7bf8fd8e2a7b
Revises: 81d5f7bfd8cf
Create Date: 2026-02-26 09:43:47.569302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bf8fd8e2a7b'
down_revision: Union[str, Sequence[str], None] = '81d5f7bfd8cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('discount_type', sa.String(), nullable=False),
    sa.Column('discount_value', sa.Integer(), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('current_uses', sa.Integer(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupons_code'), 'coupons', ['code'], unique=True)
    op.create_index(op.f('ix_coupons_id'), 'coupons', ['id'], unique=False)
    op.add_column('payment_transactions', sa.Column('coupon_id', sa.Integer(), nullable=True))
    op.add_column('payment_transactions', sa.Column('discount_amount', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'payment_transactions', 'coupons', ['coupon_id'], ['id'])
    op.drop_constraint(op.f('shared_sessions_session_id_fkey'), 'shared_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'shared_sessions', 'chat_sessions', ['session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shared_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('shared_sessions_session_id_fkey'), 'shared_sessions', 'chat_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'payment_transactions', type_='foreignkey')
    op.drop_column('payment_transactions', 'discount_amount')
    op.drop_column('payment_transactions', 'coupon_id')
    op.drop_index(op.f('ix_coupons_id'), table_name='coupons')
    op.drop_index(op.f('ix_coupons_code'), table_name='coupons')
    op.drop_table('coupons')
    # ### end Alembic commands ###
