"""add_source_ids_to_chat_messages

Revision ID: aa386e2f3ad8
Revises: 02ba3f12a589
Create Date: 2026-03-27 22:00:27.126238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa386e2f3ad8'
down_revision: Union[str, Sequence[str], None] = '02ba3f12a589'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('chat_messages', sa.Column('source_ids', sa.JSON(), nullable=True))
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'source_ids')
    # ### end Alembic commands ###
