"""add_source_ids_to_chat_messages

Revision ID: aa386e2f3ad8
Revises: 02ba3f12a589
Create Date: 2026-03-27 22:00:27.126238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa386e2f3ad8'
down_revision: Union[str, Sequence[str], None] = '02ba3f12a589'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_judgments_flat_case_number'), table_name='judgments_flat')
    op.drop_index(op.f('ix_judgments_flat_citation'), table_name='judgments_flat')
    op.drop_index(op.f('ix_judgments_flat_external_id'), table_name='judgments_flat')
    op.drop_index(op.f('ix_judgments_flat_id'), table_name='judgments_flat')
    op.drop_index(op.f('ix_judgments_flat_state'), table_name='judgments_flat')
    op.drop_table('judgments_flat')
    op.drop_index(op.f('ix_session_document_texts_id'), table_name='session_document_texts')
    op.drop_index(op.f('ix_session_document_texts_session_id'), table_name='session_document_texts')
    op.drop_table('session_document_texts')
    op.add_column('chat_messages', sa.Column('source_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'source_ids')
    op.create_table('session_document_texts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('case_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('doc_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('extracted_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('session_document_texts_pkey'))
    )
    op.create_index(op.f('ix_session_document_texts_session_id'), 'session_document_texts', ['session_id'], unique=False)
    op.create_index(op.f('ix_session_document_texts_id'), 'session_document_texts', ['id'], unique=False)
    op.create_table('judgments_flat',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('external_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_statutory', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('citation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('case_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('court', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('year', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('judge', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('petitioner', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('respondent', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('decision', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('current_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('law', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('act_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('section_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rule_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rule_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notification_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('case_note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('judgments_flat_pkey'))
    )
    op.create_index(op.f('ix_judgments_flat_state'), 'judgments_flat', ['state'], unique=False)
    op.create_index(op.f('ix_judgments_flat_id'), 'judgments_flat', ['id'], unique=False)
    op.create_index(op.f('ix_judgments_flat_external_id'), 'judgments_flat', ['external_id'], unique=False)
    op.create_index(op.f('ix_judgments_flat_citation'), 'judgments_flat', ['citation'], unique=False)
    op.create_index(op.f('ix_judgments_flat_case_number'), 'judgments_flat', ['case_number'], unique=False)
    # ### end Alembic commands ###
